api = "0.4"

[buildpack]
id = "heroku/ruby"
version = "1.0.2"
name = "Ruby"
homepage = "https://github.com/heroku/buildpacks-ruby"
ruby_version = "2.6.6"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.6.6.tgz"
  dir = "vendor/ruby/heroku-18"
  [[publish.Vendor]]
  url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.6.tgz"
  dir = "vendor/ruby/heroku-20"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
