version: 2.1
orbs:
  pack: buildpacks/pack@0.2.0
  ruby: circleci/ruby@1.1.2

references:
  hatchet: &hatchet
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES=25 IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/hatchet
  pack_cnb: &pack_cnb
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/cnb
  docker_commands: &docker_commands
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/docker
  unit: &unit
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/unit
  hatchet_setup: &hatchet_setup
    run:
      name: Hatchet setup
      command: |
        bundle exec hatchet ci:setup

jobs:
  unit:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *unit
  hatchet:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *hatchet
  pack_cnb:
    machine: true
    steps:
      - checkout
      - pack/install-pack
      - ruby/install:
          version: "2.7"
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *pack_cnb
  docker_commands:
    machine: true
    steps:
      - checkout
      - pack/install-pack
      - ruby/install:
          version: "2.7"
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *docker_commands

workflows:
  version: 2
  build:
    jobs:
      - unit
      - hatchet
      - pack_cnb
      - docker_commands

