version: 2.1
orbs:
  pack: buildpacks/pack@0.2.0
  ruby: circleci/ruby@1.1.1

references:
  hatchet: &hatchet
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES=25 IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/hatchet
  pack_cnb: &pack_cnb
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/cnb
  unit: &unit
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/unit
  restore: &restore
    restore_cache:
      keys:
        - v1_bundler_deps-{{ .Environment.CIRCLE_JOB }}
  save: &save
    save_cache:
      paths:
        - ./vendor/bundle
      key: v1_bundler_deps-{{ .Environment.CIRCLE_JOB }} # CIRCLE_JOB e.g. "ruby-2.5"
  hatchet_setup: &hatchet_setup
    run:
      name: Hatchet setup
      command: |
        bundle exec hatchet ci:setup
  bundle: &bundle
    run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
        bundle update
        bundle clean

jobs:
  unit:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *hatchet_setup
      - <<: *unit
      - <<: *save
  hatchet:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *hatchet_setup
      - <<: *hatchet
      - <<: *save
  pack_cnb:
    machine: true
    steps:
      - checkout
      - pack/install-pack
      - ruby/install:
          version: '2.7'
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *pack_cnb

workflows:
  version: 2
  build:
    jobs:
      - "unit"
      - "hatchet"
      - "pack_cnb"

